SetTextBackColor(BackGroundColor);SetColor(1);I:=8;Rom_8x8;J:=6;
OutStringXY(6,I,'Hanoi k”zel‚ben tal lhat¢ kolostor-');I:=I+GetCharY+1;
OutStringXY(j,I,'ban  ll h rom gy‚m ntr£d. A szerze-');I:=I+GetCharY+1;
OutStringXY(j,I,'teseknek a sz‚ls‹ r£don 64 aranyko-');I:=I+GetCharY+1;
OutStringXY(j,I,'rongb¢l  ll¢ tornyot kell  trakniuk');I:=I+GetCharY+1;
OutStringXY(j,I,'a m sik sz‚ls‹ r£dra -a k”z‚ps‹ r£d');I:=I+GetCharY+1;
OutStringXY(j,I,'seg¡ts‚g‚vel-, £gy hogy  minden ko-');I:=I+GetCharY+1;
OutStringXY(j,I,'rong csak n la nagyobb  tm‚r‹jû ko-');I:=I+GetCharY+1;
OutStringXY(j,I,'rongra  helyezhet‹.  A  szerzetesek');I:=I+GetCharY+1;
OutStringXY(j,I,'naponta egy  korongot mozgatnak. Ha');I:=I+GetCharY+1;
OutStringXY(j,I,'az  trak st befejezt‚k, akkor lesz ');I:=I+GetCharY+1;
OutStringXY(j,I,'v‚ge a vil gnak!');I:=I+GetCharY+1;
{OutStringXY(j,I,'A feladatot  Edouard  Lucas francia');I:=I+GetCharY+1;
OutStringXY(j,I,'matematikus tal lta ki a XIX.sz-ban');}